# Generated by Django 4.1.1 on 2023-04-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_department_dep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='IIN',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='courier',
            name='IIN',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='IIN',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=15, unique=True),
        ),
    ]
