# Generated by Django 4.1.1 on 2023-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_remove_order_trusty_client_trusty_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
