# Generated by Django 4.1.1 on 2023-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_courier_photo_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
