# Generated by Django 4.1.1 on 2023-04-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_address_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='trusty',
        ),
        migrations.AddField(
            model_name='order',
            name='trustee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trustee', to='website.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='website.client'),
        ),
    ]
