# Generated by Django 4.1.1 on 2023-04-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_client_trusty_order_trustee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
