# Generated by Django 4.1.1 on 2023-04-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_courier_declined_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
