# Generated by Django 4.1.1 on 2023-04-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_address_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
