# Generated by Django 4.1.1 on 2023-04-16 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_client_code_courier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.company'),
        ),
    ]
